name: Fetch BCRA series

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"    # todos los días 12:00 UTC (ajustá si querés)
permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run fetch script (BCRA)
        run: python scripts/fetch_bcra.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(data): update BCRA Base Monetaria (auto)"
            git push
          else
            echo "No changes"
          fi
