name: Build Macro Core (from BCRA)

on:
  workflow_dispatch:
  schedule:
    - cron: "20 3 * * *"  # después del fetch del BCRA

jobs:
  build-macro-core:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyarrow

      - name: Build macro core series
        run: python scripts/build_macro_core.py

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "macro_core: update" || echo "No changes"
          git push || true
