name: Fetch DatosAR

on:
  schedule:
    - cron: "15 3 * * *" # todos los días 03:15 UTC
  workflow_dispatch:

jobs:
  fetch-datosar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pandas requests pyarrow fastparquet
      - run: python scripts/fetch_datosar_from_meta.py
      - name: Commit & push
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add data/datosar_*.parquet
          git commit -m "update DatosAR catalog+data" || echo "nada para commitear"
          git push
