name: Fetch BCRA Base Monetaria

on:
  # Automático: 05:00 y 20:00 hora Argentina (UTC-3) => 08:00 y 23:00 UTC
  schedule:
    - cron: "0 8 * * *"     # 05:00 ART
    - cron: "0 23 * * *"    # 20:00 ART
    - cron: "22 0 * * *"   # 21:21 ART (00:21 UTC) este es de prueba

  # Manual: desde Actions -> Run workflow
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: fetch-bcra
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run fetch script
        run: python scripts/fetch_bcra.py

      - name: Commit & push if changed
        shell: bash
        run: |
          set -euo pipefail
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(data): refresh BCRA (auto)"
            git push
          fi
