# .github/workflows/fetch_datosar.yml
name: Fetch DatosAR
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install requests pandas pyarrow fastparquet
      - run: python -m scripts.fetch_datosar
      - name: Commit & push data
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add data/datosar_meta.json data/datosar_long.parquet
          git commit -m "Update DatosAR data" || echo "No changes"
          git push
