name: Fetch MECON

on:
  schedule:
    - cron: "15 2 * * *"   # todos los días 02:15 UTC
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas pyarrow requests
          fi

      - name: Run fetch script
        run: python scripts/fetch_mecon.py

      - name: Commit & push data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/mecon_long.parquet data/mecon_catalog.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(data): update MECON parquet"
            git push
          else
            echo "Sin cambios para commitear."
