name: Fetch DatosAR

on:
  schedule:
    - cron: "15 2 * * *"   # todos los días 02:15 UTC
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Build catalog + prefetch seeds
        run: |
          python scripts/fetch_datosar_catalog.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes" || (git commit -m "DatosAR fetch: update catalog/series" && git push)
