name: DatosAR catalog (local CSV)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "18 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pandas pyarrow

      - name: Build reduced catalog from local CSV
        run: python scripts/fetch_datosar_catalog.py

      - name: Commit artifacts
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/datosar_metacatalog.csv data/datosar_catalog_meta.parquet || true
          if ! git diff --cached --quiet; then
            git commit -m "DatosAR: refresh reduced catalog"
            git push
          else
            echo "No changes to commit."
          fi
